name: check-dist

on:
  pull_request:
    branches:
      - master
jobs:
  dist-in-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - name: Check if dist is up to date
        run: git diff --exit-code -- dist/
